name: clearpath_simulator_ci

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  build_and_test:
    name: humble
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: testing}
          - {ROS_DISTRO: humble, ROS_REPO: main}
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}

  clearpath_simulator_src_ci:
    name: Humble Clearpath Source
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.3
        id: action_ros_ci_step
        with:
          target-ros2-distro: humble
          package-name: |
            clearpath_generator_gz
            clearpath_gz
            clearpath_simulator
          vcs-repo-file-url: dependencies.repos
